version: '3.8'

services:
  ui-tap-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_BUCKET_URL=${NEXT_PUBLIC_BUCKET_URL}
        - NEXT_PUBLIC_INITIAL_GET_FILES_URL=${NEXT_PUBLIC_INITIAL_GET_FILES_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_BUCKET_URL=${NEXT_PUBLIC_BUCKET_URL}
      - NEXT_PUBLIC_INITIAL_GET_FILES_URL=${NEXT_PUBLIC_INITIAL_GET_FILES_URL}
    restart: unless-stopped
